language: node_js

node_js:
  - "node"
  - "lts/*"
  - "8"
  - "6"

script:
  - "npm install nyc --global"
  - "nyc npm test"

before_deploy:
  - "npm run clean"
  - "npm run build -- -P ./tsconfig.prod.json"

after_success:
  - "npm install coveralls@~3.0.0 --global"
  - "nyc report --reporter=text-lcov | coveralls"

deploy:
  skip_cleanup: true
  provider: npm
  email: "arylo.open@gmail.com"
  api_key: "${NPM_TOKEN}"
  on:
    branch: master
    node_js: "node"